---
book_repo: docs-book-developer-console
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: developer-console/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-developer-console
    ref: 'master'
  directory: developer-console/0-1
  subnav_template: developer-console_subnav_0-1.erb
  product_info:
    use_local_header: true
    latest_stable_version: 0.1
    changelog_href: http://docs.pivotal.io/developer-console/0-1/release-notes.html/
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Developer Console
    search_placeholder: Search Developer Console 0.1
    url_prefix: developer-console/0-1
    local_product_version: 0.1
    local_header_links: []
    local_header_version_list:
