---
book_repo: docs-book-developer-console
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: developer-console/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-developer-console
    ref: 'master'
  directory: developer-console/0-n
  subnav_template: developer-console_subnav_0-n.erb
  product_info:
    use_local_header: true
    latest_stable_version: 0.4
    changelog_href: http://docs-pcf-staging.cfapps.io/developer-console/0-n/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Developer Console
    search_placeholder: Search Developer Console
    url_prefix: developer-console/0-n
    local_product_version: 0.5
    local_header_links: []
    local_header_version_list:
